import nft1Image from '../../assets/images/nft1.png';
import nft2Image from '../../assets/images/nft2.png';
import nft3Image from '../../assets/images/nft3.png';
import nft4Image from '../../assets/images/nft4.png';
import nft5Image from '../../assets/images/nft5.png';
import nft6Image from '../../assets/images/nft6.png';
import nft7Image from '../../assets/images/nft7.png';
import nft8Image from '../../assets/images/nft8.png';
import testCollectionAvatar from '../../assets/images/test-collection-avatar.svg';

export const PLACEHOLDER_NFTS = [
    {
        id: 1,
        bgImage: nft1Image,
        name: 'NFT 1',
        type: 'collection',
        collectionAvatar: testCollectionAvatar,
        collectionName: 'CryptoKitties',
        collectionCount: 5,
    },
    {
        id: 2,
        bgImage: nft2Image,
        name: 'SingleNFT #2909',
        type: 'single',
    },
    {
        id: 3,
        bgImage: nft3Image,
        name: 'NFT 3',
        type: 'collection',
        collectionAvatar: testCollectionAvatar,
        collectionName: 'Crazy Collection',
        collectionCount: 5,
    },
    {
        id: 4,
        bgImage: nft4Image,
        name: 'SingleNFT #2910',
        type: 'single',
    },
    {
        id: 5,
        bgImage: nft5Image,
        name: 'NFT 7',
        type: 'collection',
        collectionAvatar: testCollectionAvatar,
        collectionName: 'CryptoPunks',
        collectionCount: 5,
    },
    {
        id: 6,
        bgImage: nft6Image,
        name: 'NFT 2',
        type: 'collection',
        collectionAvatar: testCollectionAvatar,
        collectionName: 'CryptoPunks',
        collectionCount: 5,
    },
    {
        id: 7,
        bgImage: nft7Image,
        name: 'SingleNFT #2913',
        type: 'single',
    },
    {
        id: 8,
        bgImage: nft8Image,
        name: 'NFT 6',
        type: 'collection',
        collectionAvatar: testCollectionAvatar,
        collectionName: 'CryptoKitties',
        collectionCount: 5,
    },
    {
        id: 9,
        bgImage: nft5Image,
        name: 'NFT 7',
        type: 'collection',
        collectionAvatar: testCollectionAvatar,
        collectionName: 'CryptoPunks',
        collectionCount: 5,
    },
    {
        id: 10,
        bgImage: nft6Image,
        name: 'NFT 2',
        type: 'collection',
        collectionAvatar: testCollectionAvatar,
        collectionName: 'CryptoPunks',
        collectionCount: 5,
    },
    {
        id: 11,
        bgImage: nft7Image,
        name: 'SingleNFT #2913',
        type: 'single',
    },
    {
        id: 12,
        bgImage: nft8Image,
        name: 'NFT 6',
        type: 'collection',
        collectionAvatar: testCollectionAvatar,
        collectionName: 'CryptoKitties',
        collectionCount: 5,
    },
    {
        id: 13,
        bgImage: nft1Image,
        name: 'NFT 1',
        type: 'collection',
        collectionAvatar: testCollectionAvatar,
        collectionName: 'CryptoKitties',
        collectionCount: 5,
    },
    {
        id: 14,
        bgImage: nft2Image,
        name: 'SingleNFT #2909',
        type: 'single',
    },
    {
        id: 15,
        bgImage: nft3Image,
        name: 'NFT 3',
        type: 'collection',
        collectionAvatar: testCollectionAvatar,
        collectionName: 'Crazy Collection',
        collectionCount: 5,
    },
    {
        id: 16,
        bgImage: nft4Image,
        name: 'SingleNFT #2910',
        type: 'single',
    },
    {
        id: 17,
        bgImage: nft6Image,
        name: 'NFT 2',
        type: 'collection',
        collectionAvatar: testCollectionAvatar,
        collectionName: 'CryptoPunks',
        collectionCount: 5,
    },
    {
        id: 18,
        bgImage: nft7Image,
        name: 'SingleNFT #2913',
        type: 'single',
    },
    {
        id: 19,
        bgImage: nft8Image,
        name: 'NFT 6',
        type: 'collection',
        collectionAvatar: testCollectionAvatar,
        collectionName: 'CryptoKitties',
        collectionCount: 5,
    },
    {
        id: 20,
        bgImage: nft1Image,
        name: 'NFT 1',
        type: 'collection',
        collectionAvatar: testCollectionAvatar,
        collectionName: 'CryptoKitties',
        collectionCount: 5,
    },
    {
        id: 21,
        bgImage: nft8Image,
        name: 'NFT 6',
        type: 'collection',
        collectionAvatar: testCollectionAvatar,
        collectionName: 'CryptoKitties',
        collectionCount: 5,
    },
    {
        id: 22,
        bgImage: nft1Image,
        name: 'NFT 1',
        type: 'collection',
        collectionAvatar: testCollectionAvatar,
        collectionName: 'CryptoKitties',
        collectionCount: 5,
    },
    {
        id: 23,
        bgImage: nft2Image,
        name: 'SingleNFT #2909',
        type: 'single',
    },
    {
        id: 24,
        bgImage: nft3Image,
        name: 'NFT 3',
        type: 'collection',
        collectionAvatar: testCollectionAvatar,
        collectionName: 'Crazy Collection',
        collectionCount: 5,
    },
    {
        id: 25,
        bgImage: nft4Image,
        name: 'SingleNFT #2910',
        type: 'single',
    },
    {
        id: 26,
        bgImage: nft5Image,
        name: 'NFT 7',
        type: 'collection',
        collectionAvatar: testCollectionAvatar,
        collectionName: 'CryptoPunks',
        collectionCount: 5,
    },
    {
        id: 27,
        bgImage: nft6Image,
        name: 'NFT 2',
        type: 'collection',
        collectionAvatar: testCollectionAvatar,
        collectionName: 'CryptoPunks',
        collectionCount: 5,
    },
    {
        id: 28,
        bgImage: nft1Image,
        name: 'NFT 1',
        type: 'collection',
        collectionAvatar: testCollectionAvatar,
        collectionName: 'CryptoKitties',
        collectionCount: 5,
    },
    {
        id: 29,
        bgImage: nft2Image,
        name: 'SingleNFT #2909',
        type: 'single',
    },
    {
        id: 30,
        bgImage: nft3Image,
        name: 'NFT 3',
        type: 'collection',
        collectionAvatar: testCollectionAvatar,
        collectionName: 'Crazy Collection',
        collectionCount: 5,
    },
];