import artistAvatar from '../assets/images/artist-avatar.svg';
import auctionImg from '../assets/images/ntf4.svg';

export const PLACEHOLDER_FUTURE_AUCTIONS = [
    {
        id: 1,
        title: 'Auction Title',
        image: auctionImg,
        artist: {
            id: 1,
            name: 'Justin 3LAU',
            avatar: artistAvatar,
        },
        startsIn: '2d : 5h : 20m',
        winners: 35,
        nftsPerWinner: '10-7',
    },
    {
        id: 2,
        title: 'Auction Title',
        image: auctionImg,
        artist: {
            id: 1,
            name: 'Justin 3LAU',
            avatar: artistAvatar,
        },
        startsIn: '2d : 5h : 20m',
        winners: 35,
        nftsPerWinner: '10-7',
    },
    {
        id: 3,
        title: 'Auction Title',
        image: auctionImg,
        artist: {
            id: 1,
            name: 'Justin 3LAU',
            avatar: artistAvatar,
        },
        startsIn: '2d : 5h : 20m',
        winners: 35,
        nftsPerWinner: '10-7',
    },
    {
        id: 4,
        title: 'Auction Title',
        image: auctionImg,
        artist: {
            id: 1,
            name: 'Justin 3LAU',
            avatar: artistAvatar,
        },
        startsIn: '2d : 5h : 20m',
        winners: 35,
        nftsPerWinner: '10-7',
    },
    {
        id: 5,
        title: 'Auction Title',
        image: auctionImg,
        artist: {
            id: 1,
            name: 'Justin 3LAU',
            avatar: artistAvatar,
        },
        startsIn: '2d : 5h : 20m',
        winners: 35,
        nftsPerWinner: '10-7',
    },
    {
        id: 6,
        title: 'Auction Title',
        image: auctionImg,
        artist: {
            id: 1,
            name: 'Justin 3LAU',
            avatar: artistAvatar,
        },
        startsIn: '2d : 5h : 20m',
        winners: 35,
        nftsPerWinner: '10-7',
    },
    {
        id: 7,
        title: 'Auction Title',
        image: auctionImg,
        artist: {
            id: 1,
            name: 'Justin 3LAU',
            avatar: artistAvatar,
        },
        startsIn: '2d : 5h : 20m',
        winners: 35,
        nftsPerWinner: '10-7',
    },
    {
        id: 8,
        title: 'Auction Title',
        image: auctionImg,
        artist: {
            id: 1,
            name: 'Justin 3LAU',
            avatar: artistAvatar,
        },
        startsIn: '2d : 5h : 20m',
        winners: 35,
        nftsPerWinner: '10-7',
    },
    {
        id: 9,
        title: 'Auction Title',
        image: auctionImg,
        artist: {
            id: 1,
            name: 'Justin 3LAU',
            avatar: artistAvatar,
        },
        startsIn: '2d : 5h : 20m',
        winners: 35,
        nftsPerWinner: '10-7',
    },
    {
        id: 10,
        title: 'Auction Title',
        image: auctionImg,
        artist: {
            id: 1,
            name: 'Justin 3LAU',
            avatar: artistAvatar,
        },
        startsIn: '2d : 5h : 20m',
        winners: 35,
        nftsPerWinner: '10-7',
    },
    {
        id: 11,
        title: 'Auction Title',
        image: auctionImg,
        artist: {
            id: 1,
            name: 'Justin 3LAU',
            avatar: artistAvatar,
        },
        startsIn: '2d : 5h : 20m',
        winners: 35,
        nftsPerWinner: '10-7',
    },
    {
        id: 12,
        title: 'Auction Title',
        image: auctionImg,
        artist: {
            id: 1,
            name: 'Justin 3LAU',
            avatar: artistAvatar,
        },
        startsIn: '2d : 5h : 20m',
        winners: 35,
        nftsPerWinner: '10-7',
    },
    {
        id: 13,
        title: 'Auction Title',
        image: auctionImg,
        artist: {
            id: 1,
            name: 'Justin 3LAU',
            avatar: artistAvatar,
        },
        startsIn: '2d : 5h : 20m',
        winners: 35,
        nftsPerWinner: '10-7',
    },
    {
        id: 14,
        title: 'Auction Title',
        image: auctionImg,
        artist: {
            id: 1,
            name: 'Justin 3LAU',
            avatar: artistAvatar,
        },
        startsIn: '2d : 5h : 20m',
        winners: 35,
        nftsPerWinner: '10-7',
    },
    {
        id: 15,
        title: 'Auction Title',
        image: auctionImg,
        artist: {
            id: 1,
            name: 'Justin 3LAU',
            avatar: artistAvatar,
        },
        startsIn: '2d : 5h : 20m',
        winners: 35,
        nftsPerWinner: '10-7',
    },
    {
        id: 16,
        title: 'Auction Title',
        image: auctionImg,
        artist: {
            id: 1,
            name: 'Justin 3LAU',
            avatar: artistAvatar,
        },
        startsIn: '2d : 5h : 20m',
        winners: 35,
        nftsPerWinner: '10-7',
    },
    {
        id: 17,
        title: 'Auction Title',
        image: auctionImg,
        artist: {
            id: 1,
            name: 'Justin 3LAU',
            avatar: artistAvatar,
        },
        startsIn: '2d : 5h : 20m',
        winners: 35,
        nftsPerWinner: '10-7',
    },
    {
        id: 18,
        title: 'Auction Title',
        image: auctionImg,
        artist: {
            id: 1,
            name: 'Justin 3LAU',
            avatar: artistAvatar,
        },
        startsIn: '2d : 5h : 20m',
        winners: 35,
        nftsPerWinner: '10-7',
    },
    {
        id: 19,
        title: 'Auction Title',
        image: auctionImg,
        artist: {
            id: 1,
            name: 'Justin 3LAU',
            avatar: artistAvatar,
        },
        startsIn: '2d : 5h : 20m',
        winners: 35,
        nftsPerWinner: '10-7',
    },
    {
        id: 20,
        title: 'Auction Title',
        image: auctionImg,
        artist: {
            id: 1,
            name: 'Justin 3LAU',
            avatar: artistAvatar,
        },
        startsIn: '2d : 5h : 20m',
        winners: 35,
        nftsPerWinner: '10-7',
    },
];