export enum BuyNFTSectionState {
  BUYER_FIXED_LISTING_BUY,
  BUYER_FIXED_LISTING_BUY_N_OFFER,
  BUYER_AUCTION_BID,
  BUYER_AUCTION_BID_N_OFFER,
  OWNER_PUT_ON_SALE,
  OWNER_FIXED_LISTING_CHANGE_PRICE,
  OWNER_AUCTION_LOWER_PRICE,
}
