export default {
  polymorphUniqId1: {
    image: 's',
    name: 'Polymorph #2647',
    skin: 'Zombie',
    event: 'Scramble',
    priceETH: '2.00',
    priceUSD: '168',
  },
  polymorphUniqId2: {
    image: 's',
    name: 'Polymorph #652',
    skin: 'Clown',
    event: 'Mint',
    priceETH: '1.00',
    priceUSD: '84',
  },
  polymorphUniqId3: {
    image: 's',
    name: 'Polymorph #871',
    skin: 'Zombie',
    event: 'Trade',
    priceETH: '1.00',
    priceUSD: '84',
  },
  polymorphUniqId33: {
    image: 's',
    name: 'Polymorph #871',
    skin: 'Monkey',
    event: 'Listed',
    priceETH: '1.00',
    priceUSD: '84',
  },
  polymorphUniqId4: {
    image: 's',
    name: 'Polymorph #871',
    skin: 'Monkey',
    event: 'Transfer',
    priceETH: '1.00',
    priceUSD: '84',
  },
  polymorphUniqId5: {
    image: 's',
    name: 'Polymorph #871',
    skin: 'Monkey',
    event: 'Listed',
    priceETH: '2.00',
    priceUSD: '84',
  },
  polymorphUniqId6: {
    image: 's',
    name: 'Polymorph #652',
    skin: 'Clown',
    event: 'Mint',
    priceETH: '1.00',
    priceUSD: '84',
  },
  polymorphUniqId7: {
    image: 's',
    name: 'Polymorph #2647',
    skin: 'Zombie',
    event: 'Scramble',
    priceETH: '2.00',
    priceUSD: '168',
  },
  polymorphUniqId8: {
    image: 's',
    name: 'Polymorph #871',
    skin: 'Zombie',
    event: 'Trade',
    priceETH: '1.00',
    priceUSD: '84',
  },
  polymorphUniqId9: {
    image: 's',
    name: 'Polymorph #652',
    skin: 'Clown',
    event: 'Mint',
    priceETH: '1.00',
    priceUSD: '84',
  },
  polymorphUniqId10: {
    image: 's',
    name: 'Polymorph #2647',
    skin: 'Zombie',
    event: 'Scramble',
    priceETH: '2.00',
    priceUSD: '168',
  },
  polymorphUniqId11: {
    image: 's',
    name: 'Polymorph #2647',
    skin: 'Zombie',
    event: 'Scramble',
    priceETH: '2.00',
    priceUSD: '168',
  },
};
