import tier_img1 from '../assets/images/tier_img1.svg';
import tier_img2 from '../assets/images/tier_img2.svg';
import tier_img3 from '../assets/images/tier_img3.svg';

import nft3 from '../assets/images/ntf3.svg';
import nft6 from '../assets/images/ntf6.svg';
import nft5 from '../assets/images/ntf5.svg';


export const AUCTIONS_DATA = [
    {
        id: 1,
        name: 'Auction super long million words name',
        auctionLink: 'universe.xyz/3LAU/auction1', 
        totalNFTs: 45,
        launchDate: '2021-03-01 09:30:16',
        endDate: '2021-03-07 16:25:20',
        total_bids: 120,
        total_bids_amount: 14,
        highest_winning_bid: 14,
        lower_winning_bid: 14,
        platinumTier: {
            name: 'Platinum Tier',
            nftsPerWinner: 3,
            winners: 5,
            totalNFTs: 15,
            nfts: [nft3, nft6, nft5],
        },
        goldTier: {
            name: 'Gold Tier',
            nftsPerWinner: 2,
            winners: 10,
            totalNFTs: 20,
            nfts: [nft3, nft6],
        },
        silverTier: {
            name: 'Silver Tier',
            nftsPerWinner: 1,
            winners: 20,
            totalNFTs: 20,
            nfts: [nft3],
        },
    },
    {
        id: 2,
        name: 'Auction 2',
        auctionLink: 'universe.xyz/3LAU/auction2',
        totalNFTs: 45,
        launchDate: '2021-03-01 09:10:06',
        endDate: '2021-03-08 16:25:26',
        total_bids: 120,
        total_bids_amount: 14,
        highest_winning_bid: 14,
        lower_winning_bid: 14,
        platinumTier: {
            name: 'Platinum Tier',
            nftsPerWinner: 3,
            winners: 5,
            totalNFTs: 15,
            nfts: [nft3, nft6, nft5],
        },
        goldTier: {
            name: 'Gold Tier',
            nftsPerWinner: 2,
            winners: 10,
            totalNFTs: 20,
            nfts: [nft3, nft6],
        },
        silverTier: {
            name: 'Silver Tier',
            nftsPerWinner: 1,
            winners: 20,
            totalNFTs: 20,
            nfts: [nft3],
        },
    },
    {
        id: 3,
        name: 'Auction 3',
        auctionLink: 'universe.xyz/3LAU/auction3', 
        totalNFTs: 45,
        launchDate: '2020-03-08 16:25:26',
        endDate: '2021-01-08 03:05:20',
        total_bids: 120,
        total_bids_amount: 14,
        highest_winning_bid: 14,
        lower_winning_bid: 14,
        platinumTier: {
            name: 'Platinum Tier',
            nftsPerWinner: 3,
            winners: 5,
            totalNFTs: 15,
            nfts: [nft3, nft6, nft5],
        },
        goldTier: {
            name: 'Gold Tier',
            nftsPerWinner: 2,
            winners: 10,
            totalNFTs: 20,
            nfts: [nft3, nft6],
        },
        silverTier: {
            name: 'Silver Tier',
            nftsPerWinner: 1,
            winners: 20,
            totalNFTs: 20,
            nfts: [nft3],
        },
    },
    {
        id: 4,
        name: 'Auction 4',
        auctionLink: 'universe.xyz/3LAU/auction4', 
        totalNFTs: 45,
        launchDate: '2021-03-01 09:30:16',
        endDate: '2021-03-07 16:25:20',
        total_bids: 120,
        total_bids_amount: 14,
        highest_winning_bid: 14,
        lower_winning_bid: 14,
        platinumTier: {
            name: 'Platinum Tier',
            nftsPerWinner: 3,
            winners: 5,
            totalNFTs: 15,
            nfts: [nft3, nft6, nft5],
        },
        goldTier: {
            name: 'Gold Tier',
            nftsPerWinner: 2,
            winners: 10,
            totalNFTs: 20,
            nfts: [nft3, nft6],
        },
        silverTier: {
            name: 'Silver Tier',
            nftsPerWinner: 1,
            winners: 20,
            totalNFTs: 20,
            nfts: [nft3],
        },
    },
    {
        id: 5,
        name: 'Auction 5',
        auctionLink: 'universe.xyz/3LAU/auction5',
        totalNFTs: 45,
        launchDate: '2021-03-01 09:10:06',
        endDate: '2021-03-08 16:25:26',
        total_bids: 120,
        total_bids_amount: 14,
        highest_winning_bid: 14,
        lower_winning_bid: 14,
        platinumTier: {
            name: 'Platinum Tier',
            nftsPerWinner: 3,
            winners: 5,
            totalNFTs: 15,
            nfts: [nft3, nft6, nft5],
        },
        goldTier: {
            name: 'Gold Tier',
            nftsPerWinner: 2,
            winners: 10,
            totalNFTs: 20,
            nfts: [nft3, nft6],
        },
        silverTier: {
            name: 'Silver Tier',
            nftsPerWinner: 1,
            winners: 20,
            totalNFTs: 20,
            nfts: [nft3],
        },
    },
    {
        id: 6,
        name: 'Auction 6',
        auctionLink: 'universe.xyz/3LAU/auction6', 
        totalNFTs: 45,
        launchDate: '2020-03-08 16:25:26',
        endDate: '2021-01-08 03:05:20',
        total_bids: 120,
        total_bids_amount: 14,
        highest_winning_bid: 14,
        lower_winning_bid: 14,
        platinumTier: {
            name: 'Platinum Tier',
            nftsPerWinner: 3,
            winners: 5,
            totalNFTs: 15,
            nfts: [nft3, nft6, nft5],
        },
        goldTier: {
            name: 'Gold Tier',
            nftsPerWinner: 2,
            winners: 10,
            totalNFTs: 20,
            nfts: [nft3, nft6],
        },
        silverTier: {
            name: 'Silver Tier',
            nftsPerWinner: 1,
            winners: 20,
            totalNFTs: 20,
            nfts: [nft3],
        },
    },
    {
        id: 7,
        name: 'Auction 7',
        auctionLink: 'universe.xyz/3LAU/auction7', 
        totalNFTs: 45,
        launchDate: '2021-03-01 09:30:16',
        endDate: '2021-03-07 16:25:20',
        total_bids: 120,
        total_bids_amount: 14,
        highest_winning_bid: 14,
        lower_winning_bid: 14,
        platinumTier: {
            name: 'Platinum Tier',
            nftsPerWinner: 3,
            winners: 5,
            totalNFTs: 15,
            nfts: [nft3, nft6, nft5],
        },
        goldTier: {
            name: 'Gold Tier',
            nftsPerWinner: 2,
            winners: 10,
            totalNFTs: 20,
            nfts: [nft3, nft6],
        },
        silverTier: {
            name: 'Silver Tier',
            nftsPerWinner: 1,
            winners: 20,
            totalNFTs: 20,
            nfts: [nft3],
        },
    },
    {
        id: 8,
        name: 'Auction 8',
        auctionLink: 'universe.xyz/3LAU/auction8',
        totalNFTs: 45,
        launchDate: '2021-03-01 09:10:06',
        endDate: '2021-03-08 16:25:26',
        total_bids: 120,
        total_bids_amount: 14,
        highest_winning_bid: 14,
        lower_winning_bid: 14,
        platinumTier: {
            name: 'Platinum Tier',
            nftsPerWinner: 3,
            winners: 5,
            totalNFTs: 15,
            nfts: [nft3, nft6, nft5],
        },
        goldTier: {
            name: 'Gold Tier',
            nftsPerWinner: 2,
            winners: 10,
            totalNFTs: 20,
            nfts: [nft3, nft6],
        },
        silverTier: {
            name: 'Silver Tier',
            nftsPerWinner: 1,
            winners: 20,
            totalNFTs: 20,
            nfts: [nft3],
        },
    },
    {
        id: 9,
        name: 'Auction 9',
        auctionLink: 'universe.xyz/3LAU/auction9', 
        totalNFTs: 45,
        launchDate: '2020-03-08 16:25:26',
        endDate: '2021-01-08 03:05:20',
        total_bids: 120,
        total_bids_amount: 14,
        highest_winning_bid: 14,
        lower_winning_bid: 14,
        platinumTier: {
            name: 'Platinum Tier',
            nftsPerWinner: 3,
            winners: 5,
            totalNFTs: 15,
            nfts: [nft3, nft6, nft5],
        },
        goldTier: {
            name: 'Gold Tier',
            nftsPerWinner: 2,
            winners: 10,
            totalNFTs: 20,
            nfts: [nft3, nft6],
        },
        silverTier: {
            name: 'Silver Tier',
            nftsPerWinner: 1,
            winners: 20,
            totalNFTs: 20,
            nfts: [nft3],
        },
    },
    {
        id: 10,
        name: 'Auction 10',
        auctionLink: 'universe.xyz/3LAU/auction10', 
        totalNFTs: 45,
        launchDate: '2021-03-01 09:30:16',
        endDate: '2021-03-07 16:25:20',
        total_bids: 120,
        total_bids_amount: 14,
        highest_winning_bid: 14,
        lower_winning_bid: 14,
        platinumTier: {
            name: 'Platinum Tier',
            nftsPerWinner: 3,
            winners: 5,
            totalNFTs: 15,
            nfts: [nft3, nft6, nft5],
        },
        goldTier: {
            name: 'Gold Tier',
            nftsPerWinner: 2,
            winners: 10,
            totalNFTs: 20,
            nfts: [nft3, nft6],
        },
        silverTier: {
            name: 'Silver Tier',
            nftsPerWinner: 1,
            winners: 20,
            totalNFTs: 20,
            nfts: [nft3],
        },
    },
    {
        id: 11,
        name: 'Auction 11',
        auctionLink: 'universe.xyz/3LAU/auction11',
        totalNFTs: 45,
        launchDate: '2021-03-01 09:10:06',
        endDate: '2021-03-08 16:25:26',
        total_bids: 120,
        total_bids_amount: 14,
        highest_winning_bid: 14,
        lower_winning_bid: 14,
        platinumTier: {
            name: 'Platinum Tier',
            nftsPerWinner: 3,
            winners: 5,
            totalNFTs: 15,
            nfts: [nft3, nft6, nft5],
        },
        goldTier: {
            name: 'Gold Tier',
            nftsPerWinner: 2,
            winners: 10,
            totalNFTs: 20,
            nfts: [nft3, nft6],
        },
        silverTier: {
            name: 'Silver Tier',
            nftsPerWinner: 1,
            winners: 20,
            totalNFTs: 20,
            nfts: [nft3],
        },
    },
    {
        id: 12,
        name: 'Auction 12',
        auctionLink: 'universe.xyz/3LAU/auction12', 
        totalNFTs: 45,
        launchDate: '2020-03-08 16:25:26',
        endDate: '2021-01-08 03:05:20',
        total_bids: 120,
        total_bids_amount: 14,
        highest_winning_bid: 14,
        lower_winning_bid: 14,
        platinumTier: {
            name: 'Platinum Tier',
            nftsPerWinner: 3,
            winners: 5,
            totalNFTs: 15,
            nfts: [nft3, nft6, nft5],
        },
        goldTier: {
            name: 'Gold Tier',
            nftsPerWinner: 2,
            winners: 10,
            totalNFTs: 20,
            nfts: [nft3, nft6],
        },
        silverTier: {
            name: 'Silver Tier',
            nftsPerWinner: 1,
            winners: 20,
            totalNFTs: 20,
            nfts: [nft3],
        },
    },
    {
        id: 13,
        name: 'Auction 13',
        auctionLink: 'universe.xyz/3LAU/auction13', 
        totalNFTs: 45,
        launchDate: '2021-03-01 09:30:16',
        endDate: '2021-03-07 16:25:20',
        total_bids: 120,
        total_bids_amount: 14,
        highest_winning_bid: 14,
        lower_winning_bid: 14,
        platinumTier: {
            name: 'Platinum Tier',
            nftsPerWinner: 3,
            winners: 5,
            totalNFTs: 15,
            nfts: [nft3, nft6, nft5],
        },
        goldTier: {
            name: 'Gold Tier',
            nftsPerWinner: 2,
            winners: 10,
            totalNFTs: 20,
            nfts: [nft3, nft6],
        },
        silverTier: {
            name: 'Silver Tier',
            nftsPerWinner: 1,
            winners: 20,
            totalNFTs: 20,
            nfts: [nft3],
        },
    },
    {
        id: 14,
        name: 'Auction super long million words name ',
        auctionLink: 'universe.xyz/3LAU/auction14',
        totalNFTs: 45,
        launchDate: '2021-03-01 09:10:06',
        endDate: '2021-03-08 16:25:26',
        total_bids: 120,
        total_bids_amount: 14,
        highest_winning_bid: 14,
        lower_winning_bid: 14,
        platinumTier: {
            name: 'Platinum Tier',
            nftsPerWinner: 3,
            winners: 5,
            totalNFTs: 15,
            nfts: [nft3, nft6, nft5],
        },
        goldTier: {
            name: 'Gold Tier',
            nftsPerWinner: 2,
            winners: 10,
            totalNFTs: 20,
            nfts: [nft3, nft6],
        },
        silverTier: {
            name: 'Silver Tier',
            nftsPerWinner: 1,
            winners: 20,
            totalNFTs: 20,
            nfts: [nft3],
        },
    },
    {
        id: 15,
        name: 'Auction 15',
        auctionLink: 'universe.xyz/3LAU/auction15', 
        totalNFTs: 45,
        launchDate: '2020-03-08 16:25:26',
        endDate: '2021-01-08 03:05:20',
        total_bids: 120,
        total_bids_amount: 14,
        highest_winning_bid: 14,
        lower_winning_bid: 14,
        platinumTier: {
            name: 'Platinum Tier',
            nftsPerWinner: 3,
            winners: 5,
            totalNFTs: 15,
            nfts: [nft3, nft6, nft5],
        },
        goldTier: {
            name: 'Gold Tier',
            nftsPerWinner: 2,
            winners: 10,
            totalNFTs: 20,
            nfts: [nft3, nft6],
        },
        silverTier: {
            name: 'Silver Tier',
            nftsPerWinner: 1,
            winners: 20,
            totalNFTs: 20,
            nfts: [nft3],
        },
    },
]

export const ACTIVE_ACTIONS_DATA = [];
export const FUTURE_ACTIONS_DATA = [];
export const PAST_ACTIONS_DATA = [];